import { useEffect, useMemo, useState } from "react";
import { ApiClient } from "./api/client";
import { clearSession, getSession, setSession } from "./auth/session";
import { SalesOrdersPage } from "./modules/sales-orders/SalesOrdersPage";
import { InvoicesPage } from "./modules/invoices/InvoicesPage";

const modules = [["dashboard","لوحة التحكم"],["customers","العملاء"],["sales","المبيعات"],["invoices","الفواتير"],["payments","التحصيل والمدفوعات"],["delivery","التوصيل"],["accounting","المحاسبة"]] as const;
type Customer={id:string;type:"individual"|"business";displayName:string;phone:string|null;email:string|null;status:string};
type Page<T>={data:T[];meta:{limit:number;offset:number;hasMore:boolean}};

export function App(){
 const [session,setSessionState]=useState(getSession()); const [active,setActive]=useState<(typeof modules)[number][0]>("dashboard"); const [token,setToken]=useState(""); const [error,setError]=useState<string|null>(null);
 const api=useMemo(()=>new ApiClient(import.meta.env.VITE_API_BASE_URL||"/api/v1/",()=>session?.token??null),[session]);
 if(!session)return <main className="auth-page"><section className="auth-card" aria-labelledby="auth-title"><div className="brand-mark">HO</div><h1 id="auth-title">HO Network</h1><p>واجهة التشغيل العربية</p><label htmlFor="token">رمز الجلسة</label><input id="token" type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off" dir="ltr" placeholder="Bearer token"/><button type="button" onClick={()=>{if(!token.trim())return setError("أدخل رمز الجلسة.");setError(null);setSessionState(setSession(token.trim()));setToken("");}}>بدء الجلسة</button><small>لا يتم تخزين رمز الجلسة في Local Storage أو ملفات تعريف الارتباط.</small>{error&&<p className="error" role="alert">{error}</p>}</section></main>;
 return <div className="app-shell"><header className="topbar"><div><strong>HO Network</strong><span>نظام التشغيل والإدارة</span></div><button className="secondary" type="button" onClick={()=>{clearSession();setSessionState(null);}}>إنهاء الجلسة</button></header><div className="workspace"><nav className="sidebar" aria-label="التنقل الرئيسي">{modules.map(([id,label])=><button className={active===id?"nav-item active":"nav-item"} type="button" key={id} onClick={()=>setActive(id)}>{label}</button>)}</nav><main className="content"><section className="page-heading"><div><span className="eyebrow">الوحدة الحالية</span><h1>{modules.find(([id])=>id===active)?.[1]}</h1></div><span className="status">جلسة نشطة</span></section>{active==="dashboard"?<Dashboard api={api}/>:active==="customers"?<Customers api={api}/>:active==="sales"?<SalesOrdersPage api={api}/>:active==="invoices"?<InvoicesPage api={api}/>:<section className="panel"><h2>{modules.find(([id])=>id===active)?.[1]}</h2><p>تم تأسيس مساحة الوحدة. ربط العمليات الفعلية سيُضاف فوق عقد API الحالية دون تخزين بيانات مالية محليًا.</p></section>}</main></div></div>;
}
function Dashboard({api}:{api:ApiClient}){const[state,setState]=useState<"idle"|"loading"|"ready"|"error">("idle");const[message,setMessage]=useState("لم يتم الاتصال بالـAPI بعد.");async function checkApi(){setState("loading");try{await api.get("customers?limit=1&offset=0");setState("ready");setMessage("تم الاتصال بالـAPI بنجاح.");}catch(e){setState("error");setMessage(e instanceof Error?e.message:"تعذر الاتصال بالـAPI.");}}return <div className="dashboard-grid"><section className="panel hero-panel"><span className="eyebrow">Foundation / v1</span><h2>مساحة التشغيل الأساسية</h2><p>واجهة RTL قابلة للتوسع فوق API الحالية، مع فصل واضح بين الجلسة، النقل، والوحدات.</p><button type="button" onClick={()=>void checkApi()} disabled={state==="loading"}>{state==="loading"?"جارٍ التحقق…":"اختبار اتصال API"}</button><p className={state==="error"?"error":state==="ready"?"success":"muted"} role="status">{message}</p></section><section className="panel"><h2>مبادئ الحماية</h2><ul><li>رمز المصادقة في الذاكرة فقط.</li><li>لا يوجد cache لبيانات API في Service Worker.</li><li>العقود المالية تبقى مصدرها الـAPI وقاعدة البيانات.</li><li>الواجهة لا تتجاوز صلاحيات الخادم.</li></ul></section></div>;}
function Customers({api}:{api:ApiClient}){const limit=25;const[page,setPage]=useState<Page<Customer>|null>(null);const[offset,setOffset]=useState(0);const[state,setState]=useState<"idle"|"loading"|"error">("idle");const[error,setError]=useState<string|null>(null);const[name,setName]=useState("");const[type,setType]=useState<"individual"|"business">("individual");const[phone,setPhone]=useState("");const[email,setEmail]=useState("");const[creating,setCreating]=useState(false);
 async function load(nextOffset=offset){setState("loading");setError(null);try{setPage(await api.get<Page<Customer>>(`customers?limit=${limit}&offset=${nextOffset}`));setOffset(nextOffset);setState("idle");}catch(e){setState("error");setError(e instanceof Error?e.message:"تعذر تحميل العملاء.");}}
 useEffect(()=>{void load(0);},[]);
 async function create(){if(name.trim().length<2)return setError("اسم العميل يجب أن يحتوي على حرفين على الأقل.");setCreating(true);setError(null);try{await api.post<Customer>("customers",{type,displayName:name,phone:phone||null,email:email||null,notes:null},crypto.randomUUID());setName("");setPhone("");setEmail("");setType("individual");await load(offset);}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء العميل.");}finally{setCreating(false);}}
 return <div className="customers-page"><section className="panel"><div className="section-heading"><div><span className="eyebrow">سجل العملاء</span><h2>العملاء النشطون</h2></div><button className="secondary" type="button" onClick={()=>void load(offset)} disabled={state==="loading"}>تحديث</button></div><div className="form-grid"><label>الاسم<input value={name} onChange={e=>setName(e.target.value)} maxLength={200}/></label><label>النوع<select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="individual">فرد</option><option value="business">منشأة</option></select></label><label>الهاتف<input value={phone} onChange={e=>setPhone(e.target.value)} maxLength={50}/></label><label>البريد الإلكتروني<input type="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={320}/></label><button type="button" onClick={()=>void create()} disabled={creating}>{creating?"جارٍ الإنشاء…":"إضافة عميل"}</button></div>{error&&<p className="error" role="alert">{error}</p>}</section><section className="panel">{state==="loading"&&<p className="muted">جارٍ تحميل العملاء…</p>}{page&&<div className="table-wrap"><table><thead><tr><th>الاسم</th><th>النوع</th><th>الهاتف</th><th>البريد</th><th>الحالة</th></tr></thead><tbody>{page.data.length===0?<tr><td colSpan={5}>لا توجد نتائج.</td></tr>:page.data.map(c=><tr key={c.id}><td>{c.displayName}</td><td>{c.type==="business"?"منشأة":"فرد"}</td><td dir="ltr">{c.phone||"—"}</td><td dir="ltr">{c.email||"—"}</td><td>{c.status==="active"?"نشط":c.status}</td></tr>)}</tbody></table></div>}{page&&<div className="pager"><button className="secondary" type="button" disabled={offset===0||state==="loading"} onClick={()=>void load(Math.max(0,offset-limit))}>السابق</button><span>الصفحة {Math.floor(offset/limit)+1}</span><button className="secondary" type="button" disabled={!page.meta.hasMore||state==="loading"} onClick={()=>void load(offset+limit)}>التالي</button></div>}</section></div>;}
