import React, { useCallback, useEffect, useMemo, useState } from "react";
import type { ApiClient } from "../../api/client";
import { DataTable, type Column } from "../../components/common/DataTable";
import { Pagination } from "../../components/common/Pagination";
import { ResponsiveCardList } from "../../components/common/ResponsiveCardList";
import { FeedbackState } from "../../components/common/FeedbackState";
import { StatusBadge } from "../../components/common/StatusBadge";
import { ConfirmDialog } from "../../components/dialogs/ConfirmDialog";

type DeliveryStatus = "pending"|"assigned"|"out_for_delivery"|"delivered"|"failed"|"returned"|"cancelled";
type DeliveryType = "internal"|"external";
interface Delivery {
  id:string; deliveryNumber:string; deliveryType:DeliveryType; customerId:string|null; salesOrderId:string|null;
  invoiceId:string|null; assignedDriverId:string|null; status:DeliveryStatus; address:string|null;
  contactName:string|null; contactPhone:string|null; notes:string|null; createdAt:string; assignedAt:string|null;
  outForDeliveryAt:string|null; deliveredAt:string|null; failedAt:string|null; returnedAt:string|null; cancelledAt:string|null;
}
interface Page<T>{data:T[];meta:{limit:number;offset:number;hasMore:boolean}}
interface Customer{id:string;displayName:string;status:string}
interface Detail{deliveryOrder:Delivery;receivable:{invoiceId:string;customerId:string;total:string;allocated:string;outstanding:string;currencyCode:string}|null}
interface CollectionSession{id:string;driverUserId:string;status:"open"|"closed";openedAt:string;closedAt:string|null;notes:string|null}
interface CollectionDetail{session:CollectionSession;payments:Array<{id:string;paymentId:string;paymentNumber:string;status:string;amount:string;currencyCode:string;method:string;receivedAt:string}>;settlement:Array<{currencyCode:string;method:string;expectedAmount:string;countedAmount:string;differenceAmount:string}>}

const labels:Record<DeliveryStatus,string>={pending:"معلّق",assigned:"مسند",out_for_delivery:"خرج للتوصيل",delivered:"تم التسليم",failed:"فشل",returned:"مرتجع",cancelled:"ملغى"};
const typeLabels:Record<DeliveryType,string>={internal:"داخلي",external:"خارجي"};
const nextStatus=(s:DeliveryStatus):DeliveryStatus|null=>s==="pending"?"assigned":s==="assigned"?"out_for_delivery":s==="out_for_delivery"?"delivered":s==="failed"?"assigned":null;
const key=()=>crypto.randomUUID();

export const DeliveryPage:React.FC<{api:ApiClient}>=({api})=>{
 const limit=25; const [page,setPage]=useState<Page<Delivery>|null>(null); const [offset,setOffset]=useState(0);
 const [state,setState]=useState<"idle"|"loading"|"error">("idle"); const [error,setError]=useState<string|null>(null);
 const [status,setStatus]=useState<DeliveryStatus|"all">("all"); const [search,setSearch]=useState("");
 const [customers,setCustomers]=useState<Customer[]>([]); const [selected,setSelected]=useState<Detail|null>(null);
 const [createOpen,setCreateOpen]=useState(false); const [action,setAction]=useState<{item:Delivery;next:DeliveryStatus}|null>(null);
 const [busy,setBusy]=useState(false); const [toast,setToast]=useState<string|null>(null); const [actionError,setActionError]=useState<string|null>(null);
 const [collection,setCollection]=useState<CollectionDetail|null>(null); const [sessionId,setSessionId]=useState("");

 const load=useCallback(async(target:number)=>{setState("loading");setError(null);try{const q=status==="all"?"":`&status=${status}`;const r=await api.get<Page<Delivery>>(`delivery-orders?limit=${limit}&offset=${target}${q}`);setPage(r);setOffset(target);setState("idle")}catch(e){setState("error");setError(e instanceof Error?e.message:"تعذر تحميل طلبات التوصيل.")}},[api,status]);
 const loadCustomers=useCallback(async()=>{try{const r=await api.get<Page<Customer>>("customers?limit=200&offset=0");setCustomers(r.data)}catch{}},[api]);
 useEffect(()=>{void load(0);void loadCustomers()},[load,loadCustomers]);
 const customerMap=useMemo(()=>new Map(customers.map(c=>[c.id,c.displayName])),[customers]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return (page?.data??[]).filter(d=>!q||d.deliveryNumber.toLowerCase().includes(q)||(d.customerId&&((customerMap.get(d.customerId)||"").toLowerCase().includes(q)))||d.assignedDriverId?.toLowerCase().includes(q))},[page?.data,search,customerMap]);
 const refresh=async()=>{await load(offset)};
 async function transition(){if(!action)return;setBusy(true);setActionError(null);try{await api.post(`delivery-orders/${action.item.id}/status`,{status:action.next},key());setToast(`تم تحديث الحالة إلى ${labels[action.next]}.`);setAction(null);await refresh()}catch(e){setActionError(e instanceof Error?e.message:"تعذر تحديث الحالة.")}finally{setBusy(false)}}
 async function openDetail(d:Delivery){try{setSelected(await api.get<Detail>(`delivery-orders/${d.id}`))}catch(e){setActionError(e instanceof Error?e.message:"تعذر تحميل التفاصيل.")}}
 async function openSession(){setBusy(true);setActionError(null);try{const r=await api.post<CollectionSession>("driver-collections",{driverUserId:sessionId},key());setToast("تم فتح جلسة التحصيل.");setSessionId(r.id);await loadCollection(r.id)}catch(e){setActionError(e instanceof Error?e.message:"تعذر فتح جلسة التحصيل.")}finally{setBusy(false)}}
 async function loadCollection(id:string){try{setCollection(await api.get<CollectionDetail>(`driver-collections/${id}`))}catch(e){setActionError(e instanceof Error?e.message:"تعذر تحميل جلسة التحصيل.")}}
 async function closeSession(){if(!collection)return;setBusy(true);try{await api.post(`driver-collections/${collection.session.id}/close`,{counts:[],notes:null},key());setToast("تم إغلاق جلسة التحصيل.");await loadCollection(collection.session.id)}catch(e){setActionError(e instanceof Error?e.message:"تعذر إغلاق الجلسة.")}finally{setBusy(false)}}

 const columns:Column<Delivery>[]=[
  {key:"deliveryNumber",header:"رقم الطلب",dir:"ltr",render:d=><strong>{d.deliveryNumber}</strong>},
  {key:"deliveryType",header:"النوع",render:d=>typeLabels[d.deliveryType]},
  {key:"customerId",header:"العميل",render:d=>d.customerId?(customerMap.get(d.customerId)||d.customerId):"—"},
  {key:"assignedDriverId",header:"السائق",dir:"ltr",render:d=>d.assignedDriverId||"غير مسند"},
  {key:"status",header:"الحالة",render:d=><StatusBadge status={d.status} label={labels[d.status]}/>},
  {key:"id",header:"الإجراءات",render:d=><div style={{display:"flex",gap:".4rem",flexWrap:"wrap"}}><button className="ho-btn ho-btn-secondary ho-btn-sm" onClick={()=>void openDetail(d)}>التفاصيل</button>{nextStatus(d.status)&&<button className="ho-btn ho-btn-primary ho-btn-sm" onClick={()=>setAction({item:d,next:nextStatus(d.status)!})}>{labels[nextStatus(d.status)!]}</button>}</div>}
 ];
 return <div>
  {toast&&<div className="ho-alert ho-alert-success" role="status" style={{marginBottom:"1rem"}}>{toast}</div>}
  {actionError&&<div className="ho-alert ho-alert-danger" role="alert" style={{marginBottom:"1rem"}}>{actionError}</div>}
  <header className="ho-page-header"><div><h1 className="ho-page-header-title">التوصيل والتحصيل للسائقين</h1><p className="ho-page-header-desc">إدارة طلبات التوصيل، الإسناد، دورة الحالة، وجلسة التحصيل دون تجاوز حدود السائق والذمة المالية.</p></div><div className="ho-page-header-actions"><button className="ho-btn ho-btn-secondary" onClick={()=>void refresh()} disabled={state==="loading"}>تحديث</button><button className="ho-btn ho-btn-primary" onClick={()=>setCreateOpen(true)}>+ إنشاء طلب توصيل</button></div></header>
  <section className="panel">
   {state==="loading"&&!page?<FeedbackState mode="loading" title="جارٍ تحميل طلبات التوصيل..." />:state==="error"&&!page?<FeedbackState mode="error" title="تعذر تحميل التوصيل" message={error||undefined} onRetry={()=>void load(offset)}/>:page?.data.length===0?<FeedbackState mode="empty" title="لا توجد طلبات توصيل" message="أنشئ طلب التوصيل من الواجهة التشغيلية." onAction={()=>setCreateOpen(true)} actionLabel="إنشاء طلب"/>:
   <><div className="ho-toolbar" role="search"><input className="ho-input ho-input-sm" type="search" placeholder="بحث برقم الطلب أو العميل أو معرف السائق..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="ho-select ho-select-sm" value={status} onChange={e=>setStatus(e.target.value as DeliveryStatus|"all")}><option value="all">كل الحالات</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="ho-desktop-only"><DataTable data={filtered} columns={columns} keyExtractor={d=>d.id} caption="طلبات التوصيل"/></div><div className="ho-mobile-only"><ResponsiveCardList items={filtered} keyExtractor={d=>d.id} renderCard={d=><div className="ho-customer-card"><div className="ho-customer-card-header"><div><strong dir="ltr">{d.deliveryNumber}</strong><div>{d.customerId?(customerMap.get(d.customerId)||d.customerId):typeLabels[d.deliveryType]}</div></div><StatusBadge status={d.status} label={labels[d.status]}/></div><div className="ho-customer-card-details"><div className="ho-customer-card-row"><span>السائق:</span><span dir="ltr">{d.assignedDriverId||"غير مسند"}</span></div><div className="ho-customer-card-row"><span>العنوان:</span><span>{d.address||"—"}</span></div></div><button className="ho-btn ho-btn-secondary" style={{width:"100%"}} onClick={()=>void openDetail(d)}>التفاصيل</button></div>}/></div><Pagination offset={offset} limit={limit} hasMore={page!.meta.hasMore} onPageChange={o=>void load(o)} disabled={state==="loading"}/></>}
  </section>
  <section className="panel" style={{marginTop:"1rem"}}><div className="ho-page-header" style={{marginBottom:"1rem"}}><div><h2 className="ho-page-header-title" style={{fontSize:"1.1rem"}}>جلسة التحصيل</h2><p className="ho-page-header-desc">السائق يفتح جلسته الخاصة فقط؛ الإغلاق يحسب فروقات التسوية من الدفعات المسجلة.</p></div></div><div className="ho-form-grid"><label className="ho-form-field"><span className="ho-label">معرف جلسة التحصيل</span><input className="ho-input" dir="ltr" value={sessionId} onChange={e=>setSessionId(e.target.value)} placeholder="UUID للجلسة الموجودة"/></label><div style={{display:"flex",alignItems:"end",gap:".5rem",flexWrap:"wrap"}}><button className="ho-btn ho-btn-primary" disabled={busy||!sessionId.trim()} onClick={()=>void openSession()}>فتح/إنشاء جلسة للسائق</button><button className="ho-btn ho-btn-secondary" disabled={busy||!sessionId.trim()} onClick={()=>void loadCollection(sessionId.trim())}>تحميل الجلسة</button></div></div>{collection&&<div style={{marginTop:"1rem"}}><div className="ho-customer-card"><div className="ho-customer-card-header"><div><strong dir="ltr">{collection.session.id}</strong><div>السائق: <span dir="ltr">{collection.session.driverUserId}</span></div></div><StatusBadge status={collection.session.status==="open"?"confirmed":"voided"} label={collection.session.status==="open"?"مفتوحة":"مغلقة"}/></div><div className="ho-customer-card-details"><div className="ho-customer-card-row"><span>الدفعات:</span><span>{collection.payments.length}</span></div><div className="ho-customer-card-row"><span>آخر فتح:</span><span>{new Date(collection.session.openedAt).toLocaleString("ar-EG")}</span></div></div>{collection.session.status==="open"&&<button className="ho-btn ho-btn-danger" disabled={busy} onClick={()=>void closeSession()}>إغلاق الجلسة وتسوية العد</button>}</div>{collection.settlement.length>0&&<div style={{marginTop:".75rem"}}>{collection.settlement.map((s,i)=><div key={i} className="ho-customer-card" style={{marginBottom:".5rem"}}><div className="ho-customer-card-row"><span>{s.currencyCode} · {s.method}</span><span dir="ltr">المتوقع {s.expectedAmount} / المعدود {s.countedAmount} / الفرق {s.differenceAmount}</span></div></div>)}</div>}</div>}</section>
  <CreateDeliveryDialog api={api} customers={customers} open={createOpen} onClose={()=>setCreateOpen(false)} onSuccess={async()=>{setCreateOpen(false);setToast("تم إنشاء طلب التوصيل.");await refresh()}}/>
  {selected&&<DeliveryDetailDialog api={api} detail={selected} onClose={()=>setSelected(null)} onChanged={async()=>{setSelected(await api.get<Detail>(`delivery-orders/${selected.deliveryOrder.id}`));await refresh()}}/>}
  {action&&<ConfirmDialog isOpen title={`تغيير الحالة إلى ${labels[action.next]}`} description={`سيتم نقل ${action.item.deliveryNumber} من ${labels[action.item.status]} إلى ${labels[action.next]} وفق دورة الحياة المعتمدة.`} confirmLabel="تنفيذ" cancelLabel="تراجع" isProcessing={busy} onConfirm={()=>void transition()} onCancel={()=>{if(!busy)setAction(null)}}/>}
 </div>;
};

function CreateDeliveryDialog({api,customers,open,onClose,onSuccess}:{api:ApiClient;customers:Customer[];open:boolean;onClose:()=>void;onSuccess:()=>Promise<void>}) {
 const [v,setV]=useState({deliveryType:"external" as DeliveryType,customerId:"",invoiceId:"",salesOrderId:"",assignedDriverId:"",address:"",contactName:"",contactPhone:"",notes:""});const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);if(!open)return null;
 const valid=v.deliveryType==="internal"?true:!!v.customerId&&!!v.invoiceId;
 async function submit(e:React.FormEvent){e.preventDefault();if(!valid||busy)return;setBusy(true);setError(null);try{await api.post("delivery-orders",{deliveryType:v.deliveryType,customerId:v.deliveryType==="external"?v.customerId:null,invoiceId:v.deliveryType==="external"?v.invoiceId:null,salesOrderId:v.salesOrderId||null,assignedDriverId:v.assignedDriverId||null,address:v.address||null,contactName:v.contactName||null,contactPhone:v.contactPhone||null,notes:v.notes||null},key());await onSuccess()}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء طلب التوصيل.")}finally{setBusy(false)}}
 return <div className="ho-dialog-backdrop"><div className="ho-dialog ho-dialog-lg" role="dialog" aria-modal="true" aria-labelledby="delivery-create-title"><form onSubmit={submit}><div className="ho-dialog-header"><div><h2 id="delivery-create-title">إنشاء طلب توصيل</h2><p className="ho-dialog-description">التسليم الخارجي يتطلب عميلًا وفاتورة صادرة؛ الداخلي لا يحمل ذمة مالية.</p></div><button type="button" className="ho-dialog-close-btn" onClick={onClose} disabled={busy}>✕</button></div><div className="ho-dialog-body">{error&&<div className="ho-alert ho-alert-danger" role="alert">{error}</div>}<div className="ho-form-grid">
 <label className="ho-form-field"><span className="ho-label">نوع التوصيل *</span><select className="ho-select" value={v.deliveryType} onChange={e=>setV({...v,deliveryType:e.target.value as DeliveryType})}><option value="external">خارجي</option><option value="internal">داخلي</option></select></label>
 {v.deliveryType==="external"&&<><label className="ho-form-field"><span className="ho-label">العميل *</span><select className="ho-select" value={v.customerId} onChange={e=>setV({...v,customerId:e.target.value})}><option value="">اختر العميل</option>{customers.map(c=><option key={c.id} value={c.id}>{c.displayName}</option>)}</select></label><label className="ho-form-field"><span className="ho-label">معرف الفاتورة *</span><input className="ho-input" dir="ltr" value={v.invoiceId} onChange={e=>setV({...v,invoiceId:e.target.value})}/></label></>}
 <label className="ho-form-field"><span className="ho-label">معرف أمر البيع</span><input className="ho-input" dir="ltr" value={v.salesOrderId} onChange={e=>setV({...v,salesOrderId:e.target.value})}/></label>
 <label className="ho-form-field"><span className="ho-label">معرف السائق (اختياري)</span><input className="ho-input" dir="ltr" value={v.assignedDriverId} onChange={e=>setV({...v,assignedDriverId:e.target.value})}/></label>
 <label className="ho-form-field" style={{gridColumn:"1/-1"}}><span className="ho-label">العنوان</span><input className="ho-input" value={v.address} onChange={e=>setV({...v,address:e.target.value})} maxLength={2000}/></label>
 <label className="ho-form-field"><span className="ho-label">اسم جهة الاتصال</span><input className="ho-input" value={v.contactName} onChange={e=>setV({...v,contactName:e.target.value})} maxLength={255}/></label>
 <label className="ho-form-field"><span className="ho-label">هاتف جهة الاتصال</span><input className="ho-input" dir="ltr" value={v.contactPhone} onChange={e=>setV({...v,contactPhone:e.target.value})} maxLength={100}/></label>
 <label className="ho-form-field" style={{gridColumn:"1/-1"}}><span className="ho-label">ملاحظات</span><textarea className="ho-textarea" value={v.notes} onChange={e=>setV({...v,notes:e.target.value})} maxLength={2000}/></label>
 </div></div><div className="ho-dialog-footer"><button type="button" className="ho-btn ho-btn-secondary" onClick={onClose}>إلغاء</button><button className="ho-btn ho-btn-primary" disabled={!valid||busy}>{busy?"جارٍ الإنشاء...":"إنشاء الطلب"}</button></div></form></div></div>;
}

function DeliveryDetailDialog({api,detail,onClose,onChanged}:{api:ApiClient;detail:Detail;onClose:()=>void;onChanged:()=>Promise<void>}) {
 const [driver,setDriver]=useState(detail.deliveryOrder.assignedDriverId||"");const [amount,setAmount]=useState("");const [currency,setCurrency]=useState(detail.receivable?.currencyCode||"AED");const [method,setMethod]=useState("cash");const [session,setSession]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 async function assign(){if(!/^[0-9a-fA-F-]{36}$/.test(driver)||busy)return;setBusy(true);try{await api.post(`delivery-orders/${detail.deliveryOrder.id}/assign`,{driverUserId:driver},key());await onChanged()}catch(e){setError(e instanceof Error?e.message:"تعذر إسناد الطلب.")}finally{setBusy(false)}}
 async function collect(e:React.FormEvent){e.preventDefault();if(!session||!/^[1-9]\d*(\.\d{1,10})?$/.test(amount)||busy)return;setBusy(true);try{await api.post(`delivery-orders/${detail.deliveryOrder.id}/collect`,{sessionId:session,amount,currencyCode:currency,method,receivedAt:new Date().toISOString()},key());setAmount("");await onChanged()}catch(e){setError(e instanceof Error?e.message:"تعذر تسجيل التحصيل.")}finally{setBusy(false)}}
 return <div className="ho-dialog-backdrop"><div className="ho-dialog ho-dialog-lg" role="dialog" aria-modal="true"><div className="ho-dialog-header"><div><h2>{detail.deliveryOrder.deliveryNumber}</h2><p>{typeLabels[detail.deliveryOrder.deliveryType]} · {labels[detail.deliveryOrder.status]}</p></div><button className="ho-dialog-close-btn" onClick={onClose}>✕</button></div><div className="ho-dialog-body">{error&&<div className="ho-alert ho-alert-danger" role="alert">{error}</div>}<div className="ho-form-grid"><div><strong>العميل</strong><div>{detail.deliveryOrder.customerId||"—"}</div></div><div><strong>السائق</strong><div dir="ltr">{detail.deliveryOrder.assignedDriverId||"غير مسند"}</div></div><div style={{gridColumn:"1/-1"}}><strong>العنوان</strong><div>{detail.deliveryOrder.address||"—"}</div></div></div><hr/>
 <h3>إسناد السائق</h3><div className="ho-form-grid"><input className="ho-input" dir="ltr" placeholder="UUID السائق" value={driver} onChange={e=>setDriver(e.target.value)}/><button className="ho-btn ho-btn-primary" disabled={busy||detail.deliveryOrder.status!=="pending"&&detail.deliveryOrder.status!=="failed"} onClick={()=>void assign()}>إسناد</button></div>
 {detail.receivable&&<><hr/><h3>الذمة المرتبطة</h3><div className="ho-form-grid"><div>الإجمالي: <span dir="ltr">{detail.receivable.total} {detail.receivable.currencyCode}</span></div><div>المحصّل: <span dir="ltr">{detail.receivable.allocated} {detail.receivable.currencyCode}</span></div><div>المتبقي: <strong dir="ltr">{detail.receivable.outstanding} {detail.receivable.currencyCode}</strong></div></div>{["out_for_delivery","delivered"].includes(detail.deliveryOrder.status)&&<form onSubmit={collect} className="ho-form-grid" style={{marginTop:"1rem"}}><input className="ho-input" dir="ltr" inputMode="decimal" placeholder="مبلغ التحصيل" value={amount} onChange={e=>setAmount(e.target.value)}/><input className="ho-input" dir="ltr" maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/><select className="ho-select" value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">نقدي</option><option value="sham_cash">شام كاش</option></select><input className="ho-input" dir="ltr" placeholder="UUID جلسة التحصيل" value={session} onChange={e=>setSession(e.target.value)}/><button className="ho-btn ho-btn-primary" disabled={busy}>تسجيل التحصيل</button></form>}</>}</div></div></div>;
}
